### ISSUE TITLE
Action items from outage on 3/22

### ISSUE THREAD

**Issue by indirect** [bundler/bundler-api#141]
After the outage on 3/22, we came up with some action items. Please add the PR number to the todo when you check it off.
- [x] Add ENV switch for new index endpoints (#142)
- [ ] Set up pgbouncer on each dyno and increase total dynos (#143)
- [ ] Use memcached for all new index responses (#149)
- [x] Add back purging new index on Fastly, but update the memcached value beforehand (#152)
- [ ] Review all of the configuration changes and commits made to bundler-api on 3/22 (#?)

**Comment by segiddins** [comment]
Given the bundler-api is no longer in production, I think we can safely close this.
